import type { EsCanvasState, EsNode } from './types';

export function exportToCML(state: EsCanvasState): string {
  const { nodes, edges } = state;

  const aggregates = nodes.filter((n) => n.type === 'aggregate');
  const events = nodes.filter((n) => n.type === 'event');
  const commands = nodes.filter((n) => n.type === 'command');
  const actors = nodes.filter((n) => n.type === 'actor');
  const policies = nodes.filter((n) => n.type === 'policy');
  const externals = nodes.filter((n) => n.type === 'external');
  const readmodels = nodes.filter((n) => n.type === 'readmodel');

  const lines: string[] = [];
  lines.push('/* Generated by Esbuddy - Event Storming to Context Mapper */');
  lines.push('');

  // Group nodes by aggregate
  const nodesByAggregate = new Map<string, EsNode[]>();
  const standaloneNodes: EsNode[] = [];

  for (const node of [...events, ...commands]) {
    const aggId = node.data.aggregateId;
    if (aggId) {
      const group = nodesByAggregate.get(aggId) || [];
      group.push(node);
      nodesByAggregate.set(aggId, group);
    } else {
      standaloneNodes.push(node);
    }
  }

  // Write aggregates
  for (const agg of aggregates) {
    lines.push(`Aggregate ${toIdentifier(agg.data.label)} {`);
    const members = nodesByAggregate.get(agg.id) || [];
    for (const m of members) {
      if (m.type === 'event') {
        lines.push(`  DomainEvent ${toIdentifier(m.data.label)}`);
      } else if (m.type === 'command') {
        lines.push(`  Command ${toIdentifier(m.data.label)}`);
      }
    }
    lines.push('}');
    lines.push('');
  }

  // Write standalone events and commands
  for (const node of standaloneNodes) {
    if (node.type === 'event') {
      lines.push(`DomainEvent ${toIdentifier(node.data.label)}`);
    } else if (node.type === 'command') {
      lines.push(`Command ${toIdentifier(node.data.label)}`);
    }
  }
  if (standaloneNodes.length > 0) lines.push('');

  // Write actors
  for (const actor of actors) {
    lines.push(`/* Actor: ${actor.data.label} */`);
  }

  // Write policies
  for (const policy of policies) {
    lines.push(`/* Policy: ${policy.data.label} */`);
  }

  // Write external systems
  for (const ext of externals) {
    lines.push(`/* External System: ${ext.data.label} */`);
  }

  // Write read models
  for (const rm of readmodels) {
    lines.push(`/* Read Model: ${rm.data.label} */`);
  }

  if (actors.length > 0 || policies.length > 0 || externals.length > 0 || readmodels.length > 0) {
    lines.push('');
  }

  // Write flows (edges)
  if (edges.length > 0) {
    lines.push('Flow {');
    for (const edge of edges) {
      const sourceNode = nodes.find((n) => n.id === edge.source);
      const targetNode = nodes.find((n) => n.id === edge.target);
      if (sourceNode && targetNode) {
        lines.push(`  ${toIdentifier(sourceNode.data.label)} -> ${toIdentifier(targetNode.data.label)}`);
      }
    }
    lines.push('}');
  }

  return lines.join('\n');
}

function toIdentifier(label: string): string {
  return label
    .trim()
    .replace(/\s+/g, '_')
    .replace(/[^\w]/g, '')
    .replace(/^(\d)/, '_$1');
}
